version: "3.8"
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      market_net:
        ipv4_address: 172.22.2.2

  db:
    image: postgres:16
    command: ["postgres"]
    ports:
      - "${DB_FORWARD_PORT:-5432}:5432"
    volumes:
      - "./data/db:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: dev
    networks:
      market_net:
        ipv4_address: 172.22.2.4

  app:
    build: .
    environment:
      - LOG_LEVEL=INFO
      - POSTGRES_URL=postgres://postgres:dev@db:5432/postgres?connect_timeout=1
      - RABBIT_URL=amqp://guest:guest@rabbitmq:5672/
    depends_on:
      - db
      - rabbitmq
    networks:
      market_net:
        ipv4_address: 172.22.2.6

networks:
  market_net:
    external: true
